name: theturtle
version: 0.1.0.0
github: 'githubuser/theturtle'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2019 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/theturtle#readme>

dependencies:
  - base >= 4.7 && < 5
  - turtle
  - text
  - foldl
  - aeson
  - bytestring == 0.10.8.2
  - mtl == 2.2.2

library:
  source-dirs: src

executables:
  grep:
    main: Main.hs
    source-dirs: app/Grep
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theturtle
  echo:
    main: Main.hs
    source-dirs: app/Echo
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theturtle
  fs:
    main: Main.hs
    source-dirs: app/Fs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theturtle
  exec:
    main: Main.hs
    source-dirs: app/Exec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theturtle
  io:
    main: Main.hs
    source-dirs: app/Io
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theturtle

tests:
  theturtle-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theturtle
